### ISSUE TITLE
EDP47 Needs moving in to the T5 Code

### ISSUE THREAD

**Issue by parahooners** [Xinyuan-LilyGO/LilyGo-T5-Epaper-Series#17]
Hey,

So having a few of these displays the GXepd file is much better suited to the EDP47 is there plans to integrate this in this repository

**Comment by lewisxhe** [comment]
EPD47 doesn't belong to this series, so it won't be put here, it has its own repository https://github.com/Xinyuan-LilyGO/LilyGo-EPD47
