### ISSUE TITLE
Support in EspEasy firmware

### ISSUE THREAD

**Issue by jbaream** [Xinyuan-LilyGO/LilyGo-T5-Epaper-Series#18]
Hi,

It would be nice to have a plugin to control these nice eink screens from the firmware ESPEasy. Currently only Lolin ePaper screens are supported. I attach the source file of the plugin for these screens. Is it too difficult to code something similar? What do you think? I am not a expert in advanced programming as to do it. Maybe this can be accomplished by modifying the attached source file.

Best regards,

Jose.
[_P096_eInk.ino.zip](https://github.com/Xinyuan-LilyGO/LilyGo-T5-Epaper-Series/files/6719504/_P096_eInk.ino.zip)

**Comment by lewisxhe** [comment]
Looks good, I can try it. Thanks for your advice
