### ISSUE TITLE
Battery Voltage example

### ISSUE THREAD

**Issue by Martenz** [Xinyuan-LilyGO/LilyGo-T5-Epaper-Series#21]
I’m trying to understand how to read battery voltage 1s plugged to the onboard connector but can’t find some good documentation or examples specific for this board.. do I need to create a voltage divider .. is it included in the board?  

I have a 1.54 bw and a 2.13 bwr models with speaker.

I tried several how to but none of them works.. 
please help! 

Thanks,

Martino

**Comment by lewisxhe** [comment]
All boards have resistor dividers, which one do you use?

**Comment by lewisxhe** [comment]
If there is still a problem, please reopen the issue
