### ISSUE TITLE
T5 2.9” V2.2 Deep Sleep Issue

### ISSUE THREAD

**Issue by cvocvo** [Xinyuan-LilyGO/LilyGo-T5-Epaper-Series#30]
I’m using ESPHome with a T5 2.9” v2.2 epaper, and when I enter deep sleep — shortly after entering deep sleep my screen becomes weird — half white / half black display with artifacts. I will try to post a picture.

The refresh will occur in deep sleep but the display itself won’t recover. 

Any ideas? Is deep sleep supported on v2.2?

**Comment by cvocvo** [comment]
![E67EA381-CA63-4840-8080-A6BFF5AD30DB](https://user-images.githubusercontent.com/355711/183249938-e95a02b9-a188-49a2-9200-e4b1a6f35c17.jpeg)

**Comment by lewisxhe** [comment]
T5_V2.2 supports deep sleep. If the screen is refreshed after deep sleep is set, please check what is the reason for waking up. I don't use ESPHome. I will rule out the reason for the time being. you can refresh

https://github.com/Xinyuan-LilyGO/LilyGo-T5-Epaper-Series/blob/master/examples/GxEPD_Example/GxEPD_Example.ino

Check if you can sleep normally

**Comment by cvocvo** [comment]
I think you're spot on -- I played with the refresh settings a little bit and found a post with a similar issue here: https://github.com/esphome/issues/issues/2334

Once I get it dialed in, I'll post some code this week or this weekend.

**Comment by cvocvo** [comment]
I think I got it mostly sorted out; battery life still isn't great but that's a known limitation of v2.2 of the 2.9" board.
Here's what I've got for code -- I solved a bunch of problems (screen reloading issue, deep sleep, sleeping the flash, button to reload, etc.) and posted code up here: https://github.com/cvocvo/esphomeprojects/blob/main/epaper29.yaml
