### ISSUE TITLE
Is there a way to check it charger is connected? 

### ISSUE THREAD

**Issue by BatsIhor** [Xinyuan-LilyGO/LilyGo-T5-Epaper-Series#35]
Hi there, 
On other boards I used battery pin to check voltage and in case it's more than 4.3V I assume usb cable is connected. 
But is there other way to make sure charger is connected? 
My problem is that some cheap cables and chargers deliver less than 4.3V and in that case device goes to sleep while still on charger. 

Thank you
Ihor

**Comment by lewisxhe** [comment]
Based on the current circuit, it is impossible to accurately determine whether USB is inserted
