### ISSUE TITLE
incorrect pinout on the pinout sheet 

### ISSUE THREAD

**Issue by rdekens** [Xinyuan-LilyGO/LilyGo-T5-Epaper-Series#50]
couldn't get the 266 EPD to work with the examples  until I went back to  GxEPD rather than GxEPD2.
Traced it back to GxEPD using the boards.h file - and from there to the correct pinouts to the 2.66 " epd -
motably - as per the schematics - which are correct  - the Display is 
MOSI  23   : correct
MISO  17 : 
CLK 18 : correct
CS 5 : correct
RST :  16  WRONG ->  **4**
BUSY 4  WRONG -> **34**
DC not shown - > 19 -  - PIn 19 should be shown as used by the display and not available without due care

pin 17 Appears to have been unused - would have been good if it had been routed out instead of 19 , or used instead with the display.
see attatched modified diagram
![corrected_266](https://github.com/Xinyuan-LilyGO/LilyGo-T5-Epaper-Series/assets/12215022/a3a48989-b4e6-4115-bdbd-d58ed94d3ac1)

the examples need to be adjusted to account for the different pinout also

**Comment by lewisxhe** [comment]
Thanks for the feedback, I have given it and will make changes soon
